services:
    whisper-nginx:
        container_name: whisper-nginx
        image: nginx:${NGINX_VERSION}
        restart: unless-stopped
        volumes:
            - ./nginx/${VHOST_FILE}:/etc/nginx/conf.d/custom.conf
        ports:
            - "80"
        depends_on:
            - whisper-api
        environment:
            VIRTUAL_HOST: ${DOMAIN_HOST}
            SELF_SIGNED_HOST: ${SELF_SIGNED_HOST}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN_HOST}
            LETSENCRYPT_EMAIL: ${DOMAIN_EMAIL}
        networks:
            - nginx-proxy
            - whisper-api

    whisper-api:
        build:
            context: ./whisper-api
            args:
                WHISPER_API_PORT: ${WHISPER_API_PORT}
        container_name: whisper-api
        ports:
            - ${WHISPER_API_PORT}:${WHISPER_API_PORT}
        networks:
            - whisper-api
        restart: unless-stopped


networks:
    whisper-api:
    nginx-proxy:
        external: true
